Repository CSC59939/QuikBorrow, pull requests merged in 2019-12, with the labels that each got.

#116 reject all other transaction requests on approval and modified tests
  server/controllers/transactions.js
  server/models/Transaction.int.test.js
  server/models/Transaction.js
  server/services/transactions.js
  server/services/transactions.unit.test.js
Labels: enhancement, tests

#125 Add Codecov to CI for automatic test coverage reports on PRs
  .github/workflows/nodejs.yml
  client/package-lock.json
  client/package.json
  client/src/js/components/AddItemModal/__snapshots__/AddItemModal.test.js.snap
  package.json
  server/package-lock.json
  server/package.json
Labels: tests

#129 Comments backend
  server/controllers/comments.js
  server/controllers/comments.unit.test.js
  server/models/Comment.js
  server/routes/api/comments.js
  server/services/comments.js
  server/services/comments.unit.test.js
  server/services/transactions.js
Labels: enhancement

#136 Made UI more consistent
  client/src/js/components/App.js
  client/src/js/components/Homepage/Homepage.js
  client/src/js/components/Homepage/__snapshots__/Homepage.test.js.snap
  client/src/js/components/Products/ProductDetail.js
  client/src/js/components/Products/ProductList.js
  client/src/js/components/Products/__snapshots__/ProductDetail.test.js.snap
  client/src/js/components/Products/__snapshots__/ProductList.test.js.snap
  client/src/js/components/Profile/Profile.js
  client/src/js/components/Profile/ProfileCard.js
  client/src/js/components/Profile/__snapshots__/Profile.test.js.snap
  client/src/js/components/Profile/__snapshots__/ProfileCard.test.js.snap
  client/src/js/components/utils/PageContent.js
Labels: bug

#120 Yl/images
  client/src/js/components/AddItemModal/AddItemModal.js
  client/src/js/components/AddItemModal/AddItemModal.test.js
  client/src/js/components/Homepage/Homepage.js
  client/src/js/components/Homepage/__snapshots__/Homepage.test.js.snap
  client/src/js/components/Products/ProductCard.js
  client/src/js/components/Products/ProductDetail.js
  server/.eslintrc.js
  server/config/keys.js
  server/controllers/items.js
  server/controllers/users.js
  server/controllers/users.unit.test.js
  server/index.js
  server/middleware/items.js
  server/middleware/items.unit.test.js
  server/models/Item.js
  server/package-lock.json
  server/package.json
  server/routes/api/users.js
  server/uploads/2019-11-25T22-06-54.865Zgcd.PNG
  server/uploads/2019-11-25T22-09-26.227Zgcd.PNG
  server/uploads/2019-11-25T22-09-48.381Zgcd.PNG
  server/uploads/2019-11-25T22-10-19.515Zgcd.PNG
  server/uploads/2019-11-25T22-14-00.615Zgcd.PNG
  server/uploads/2019-11-25T22-24-11.495Zgcd.PNG
  server/uploads/2019-11-27T21-18-23.085Zgcd_asm_1.PNG
  server/uploads/2019-11-27T21-19-43.242Zgcd_asm_1.PNG
  server/uploads/2019-11-27T21-19-54.504Zgcd_asm_1.PNG
  server/uploads/2019-11-27T21-40-57.198Zgcd_asm_1.PNG
  server/uploads/2019-11-27T21-51-51.754Zfactorial stack frames.png
Labels: enhancement

#131 adding tests for items, removing unneeded route, adding fields to item
  server/controllers/items.js
  server/controllers/items.unit.test.js
  server/controllers/users.js
  server/models/Item.int.test.js
  server/models/Item.js
  server/routes/api/items.js
  server/services/transactions.js
Labels: enhancement, tests

#141 Setup comments frontend
  client/package-lock.json
  client/package.json
  client/src/js/actions/comments.js
  client/src/js/actions/comments.test.js
  client/src/js/actions/types.js
  client/src/js/components/Comments/Comment.js
  client/src/js/components/Comments/Comment.test.js
  client/src/js/components/Comments/CommentList.js
  client/src/js/components/Comments/CommentList.test.js
  client/src/js/components/Products/ProductDetail.js
  client/src/js/components/Products/ProductDetail.test.js
  client/src/js/components/Products/__snapshots__/ProductDetail.test.js.snap
  client/src/js/reducers/commentsReducer.js
  client/src/js/reducers/commentsReducer.test.js
  client/src/js/reducers/index.js
  server/controllers/comments.js
  server/models/Comment.js
  server/routes/api/index.js
Labels: bug, enhancement

#143 Yl/redirect to root on logout
  client/src/js/components/Navbar/SignedIn.js
  client/src/js/components/Navbar/SignedIn.test.js
  client/src/js/components/Navbar/SignedOut.js
  client/src/js/components/Navbar/SignedOut.test.js
  client/src/js/components/Navbar/__snapshots__/Navbar.test.js.snap
  client/src/js/components/Navbar/__snapshots__/SignedIn.test.js.snap
  client/src/js/components/Navbar/__snapshots__/SignedOut.test.js.snap
Labels: documentation, tests

#148 Fix codecov erroenous coverage reports (including on master branch)
  .github/workflows/nodejs.yml
Labels: bug

#156 Added docs missing to certain files
  .eslintignore
  client/src/js/components/Comments/Comment.js
  client/src/js/components/Comments/CommentList.js
  client/src/js/components/Login/Login.js
  client/src/js/components/Login/Login.test.js
  client/src/js/components/Register/Register.js
  client/src/js/components/Register/Register.test.js
Labels: documentation

#155 update Item rating
  server/controllers/items.js
  server/controllers/items.unit.test.js
  server/models/Item.js
  server/routes/api/items.js
  server/services/items.js
  server/services/items.unit.test.js
Labels: enhancement

#157 Fix comments when not logged in and spacing
  client/src/js/components/Comments/Comment.js
  client/src/js/components/Comments/Comment.test.js
  client/src/js/components/Comments/CommentList.js
  client/src/js/components/Products/ProductDetail.js
  client/src/js/components/Products/__snapshots__/ProductDetail.test.js.snap
Labels: bug

#158 Transactions On FrontEnd
  client/src/js/actions/products.js
  client/src/js/actions/products.test.js
  client/src/js/actions/types.js
  client/src/js/components/Profile/Profile.js
  client/src/js/components/Profile/Profile.test.js
  client/src/js/components/Profile/ProfileCard.js
  client/src/js/components/Profile/ProfileCard.test.js
  client/src/js/components/Profile/__snapshots__/Profile.test.js.snap
  client/src/js/components/Profile/__snapshots__/ProfileCard.test.js.snap
  client/src/js/reducers/index.js
  client/src/js/reducers/transactionsReducer.js
  client/src/js/reducers/transactionsReducer.test.js
  package-lock.json
  package.json
Labels: enhancement, tests
