Repository CSC59939/QuikBorrow, pull requests merged in 2019-11, with the labels that each got.

#24 products page
  client/package-lock.json
  client/package.json
  client/src/index.js
  client/src/js/actions/index.js
  client/src/js/actions/types.js
  client/src/js/components/App.js
  client/src/js/components/Products/ProductCard.js
  client/src/js/components/Products/ProductList.js
  client/src/js/reducers/index.js
  client/src/js/reducers/productsReducer.js
  package.json
  server/database/index.js
  server/database/models/items.js
  server/handlers/itemHandler.js
  server/index.js
  server/package-lock.json
  server/package.json
  server/routes/index.js
  server/routes/items.js
Labels: enhancement

#27 Able to render a list of product cards styled using PrimeReact onto the screen.
  client/package-lock.json
  client/package.json
  client/src/js/components/App.js
  client/src/js/components/Products/ProductCard.js
  client/src/js/components/Products/ProductList.js
  server/database/index.js
  server/package-lock.json
Labels: enhancement

#25 User reg backend
  .eslintignore
  package.json
  server/config/keys.js
  server/config/passport.js
  server/database/models/User.js
  server/index.js
  server/jest-mongodb-config.js
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/routes/api/users.js
  server/tests/User.test.js
  server/tests/users.test.js
Labels: enhancement

#42 front end user profile
  client/src/js/components/App.js
  client/src/js/components/Products/ProductCard.js
  client/src/js/components/Profile/Profile.js
  client/src/js/components/Profile/Profile.test.js
  client/src/js/components/Profile/ProfileCard.js
  client/src/js/components/Profile/__snapshots__/Profile.test.js.snap
  server/package-lock.json
Labels: enhancement

#55 Start server only after DB connected
  server/index.js
  server/services/mongodbConnect.js
Labels: enhancement

#48 unit tests for product stuff
  client/package-lock.json
  client/package.json
  client/src/js/actions/index.js
  client/src/js/components/Products/ProductCard.test.js
  client/src/js/components/Products/ProductList.js
  client/src/js/components/Products/ProductList.test.js
  client/src/js/components/Products/__snapshots__/ProductCard.test.js.snap
  client/src/js/components/Products/__snapshots__/ProductList.test.js.snap
  client/src/js/reducers/productsReducer.test.js
Labels: tests

#57 Add unit tests for items controller and services
  server/controllers/items.unit.test.js
  server/middleware/shared/validatorErrors.unit.test.js
  server/services/items.unit.test.js
Labels: tests

#56 Add lint-fix and use nodemon for npm run dev
  client/package.json
  package.json
  server/package.json
Labels: enhancement

#66 Add users controller/services unit tests, bug fix
  server/controllers/users.js
  server/controllers/users.unit.test.js
  server/services/users.js
  server/services/users.unit.test.js
Labels: tests

#70 Add Dashboard test and update Register and Login tests
  client/src/js/components/Dashboard/Dashboard.js
  client/src/js/components/Dashboard/Dashboard.test.js
  client/src/js/components/Dashboard/__snapshots__/Dashboard.test.js.snap
  client/src/js/components/Login/Login.test.js
  client/src/js/components/Register/Register.test.js
Labels: tests

#53 Yl/product details
  client/src/js/actions/index.js
  client/src/js/components/App.js
  client/src/js/components/Navbar/Navbar.js
  client/src/js/components/Products/ProductCard.js
  client/src/js/components/Products/ProductCard.test.js
  client/src/js/components/Products/ProductDetail.js
  client/src/js/components/Products/ProductList.js
  client/src/js/components/Products/__snapshots__/ProductCard.test.js.snap
  client/src/js/components/Products/__snapshots__/ProductList.test.js.snap
  client/src/js/reducers/index.js
  client/src/js/reducers/productReducer.js
Labels: enhancement

#69 simple navbar that renders based on authentication
  client/public/index.html
  client/src/index.js
  client/src/js/components/App.js
  client/src/js/components/Navbar/Navbar.js
  client/src/js/components/Navbar/SignedIn.js
  client/src/js/components/Navbar/SignedOut.js
Labels: enhancement

#75 More frontend tests
  client/src/js/actions/index.js
  client/src/js/actions/index.test.js
  client/src/js/components/Products/ProductDetail.js
  client/src/js/components/Products/ProductDetail.test.js
  client/src/js/components/Products/__snapshots__/ProductDetail.test.js.snap
  client/src/js/reducers/productReducer.test.js
Labels: tests

#86 Yl/navbar test
  client/src/js/components/Navbar/Navbar.js
  client/src/js/components/Navbar/Navbar.test.js
  client/src/js/components/Navbar/__snapshots__/Navbar.test.js.snap
Labels: tests

#85 Frontend tests
  client/package.json
  client/src/js/actions/index.test.js
  client/src/js/components/Dashboard/Dashboard.js
  client/src/js/components/Login/Login.js
  client/src/js/components/Login/Login.test.js
  client/src/js/components/Register/Register.test.js
Labels: tests

#87 added transaction
  server/controllers/transactions.js
  server/models/Transaction.js
  server/routes/api/index.js
  server/routes/api/transactions.js
  server/services/transactions.js
Labels: enhancement

#95 Setup search feature on backend
  server/controllers/items.js
  server/controllers/items.unit.test.js
  server/models/Item.js
  server/package-lock.json
  server/routes/api/items.js
  server/services/items.js
Labels: enhancement

#90 added transaction lists
  server/controllers/transactions.js
  server/models/Transaction.js
  server/routes/api/transactions.js
  server/services/transactions.js
Labels: enhancement

#101 Yl/detailed product design
  client/package-lock.json
  client/package.json
  client/src/js/components/Products/ProductDetail.js
  client/src/js/components/Products/__snapshots__/ProductDetail.test.js.snap
Labels: enhancement

#105 Add and fix most server code documentation
  server/.eslintrc.js
  server/controllers/items.js
  server/controllers/transactions.js
  server/controllers/users.js
  server/middleware/shared/validatorErrors.js
  server/middleware/shared/validators/isObjectId.js
  server/middleware/users.js
  server/models/Item.js
  server/models/Transaction.js
  server/models/User.js
  server/package-lock.json
  server/package.json
  server/routes/api/items.js
  server/routes/api/transactions.js
  server/routes/api/users.js
  server/services/items.js
  server/services/mongodbConnect.js
  server/services/transactions.js
  server/services/users.js
Labels: documentation

#109 added tests for transactions
  server/controllers/transactions.unit.test.js
  server/services/transactions.js
  server/services/transactions.unit.test.js
Labels: tests

#106 Add POST /api/users/:userId/items with auth
  server/controllers/users.js
  server/controllers/users.unit.test.js
  server/middleware/users.js
  server/middleware/users.unit.test.js
  server/routes/api/users.js
  server/services/users.js
  server/services/users.unit.test.js
Labels: enhancement

#92 added user profile reducers in redux, added testing for user profile reducer and action
  client/src/js/actions/index.js
  client/src/js/actions/index.test.js
  client/src/js/actions/types.js
  client/src/js/reducers/index.js
  client/src/js/reducers/userReducer.js
  client/src/js/reducers/userReducer.test.js
Labels: enhancement, tests

#110 quick fix on margins
  client/src/js/components/App.js
  client/src/js/components/Login/Login.js
  client/src/js/components/Login/__snapshots__/Login.test.js.snap
  client/src/js/components/Register/Register.js
  client/src/js/components/Register/__snapshots__/Register.test.js.snap
Labels: bug

#108 Add search frontend
  client/package-lock.json
  client/package.json
  client/src/js/actions/index.js
  client/src/js/actions/index.test.js
  client/src/js/actions/types.js
  client/src/js/components/Products/ProductList.js
  client/src/js/components/Products/__snapshots__/ProductList.test.js.snap
  client/src/js/components/Search/Search.js
  client/src/js/components/Search/Search.test.js
  client/src/js/reducers/productsReducer.js
  package-lock.json
  package.json
  server/routes/api/items.js
Labels: enhancement

#115 Fix log in persistence
  client/src/index.js
  client/src/js/components/App.js
  client/src/js/components/App.test.js
  client/src/js/components/Products/ProductDetail.js
Labels: bug

#117 Fix user auth error displays and changed search
  client/src/js/components/Login/Login.js
  client/src/js/components/Login/__snapshots__/Login.test.js.snap
  client/src/js/components/Products/ProductList.js
  client/src/js/components/Products/__snapshots__/ProductList.test.js.snap
  client/src/js/components/Register/Register.js
  client/src/js/components/Register/__snapshots__/Register.test.js.snap
  client/src/js/components/Search/Search.js
  client/src/js/components/Search/Search.test.js
Labels: bug

#119 Fix add item modal initial state as loading
  client/src/js/components/AddItemModal/AddItemModal.js
  client/src/js/components/AddItemModal/__snapshots__/AddItemModal.test.js.snap
Labels: bug

#118 Add action for borrowing
  client/src/js/actions/index.js
  client/src/js/actions/products.js
  client/src/js/actions/products.test.js
  client/src/js/actions/types.js
  client/src/js/reducers/productsReducer.js
Labels: enhancement

#96 Oc/profile frontend
  client/src/js/components/App.js
  client/src/js/components/Navbar/Navbar.js
  client/src/js/components/Navbar/SignedIn.js
  client/src/js/components/Profile/Profile.js
  client/src/js/components/Profile/Profile.test.js
  client/src/js/components/Profile/ProfileCard.js
  client/src/js/components/Profile/__snapshots__/Profile.test.js.snap
Labels: enhancement
